### ISSUE TITLE
App not available in some regions

### ISSUE THREAD

**Issue by rmgaray** [peoplesfeelings/Sample-Metronome#1]
I stumbled upon your blog and wanted to try this app. Unfortunately, it seems it is not available in Argentina:

![image](https://user-images.githubusercontent.com/29001707/101293107-60c3f380-37f2-11eb-979c-db457bd02065.png)

Maybe there is something you could do to make it available in my country? Otherwise, you could try to provide a version for F-droid (in case you do not need monetization from Google), or simply an APK file.

**Comment by peoplesfeelings** [comment]
No problem. I updated the Play Store listing so that it is now available in Argentina. If you don't see it then check back in a few hours because there may be some delay before it appears. The app only has English strings, which is why distribution is limitted. But, when people ask, I enable the app for their country.

**Comment by rmgaray** [comment]
Thank you!
